name: yaplingo

services:
  server:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app/app
    models:
      - llm
    tty: true

models:
  llm:
    model: "ai/llama3.2"
    runtime_flags:
      - "--no-prefill-assistant"
