name: yaplingo

services:
  server:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    volumes:
      - ./server:/server/server
    depends_on:
      - database
      - store
    models:
      - llm
    tty: true

  database:
    image: postgres:latest
    env_file: .env
    ports:
      - "5432:5432"
    volumes:
      - postgres:/var/lib/postgresql
    restart: always

  store:
    image: redis:latest
    env_file: .env
    ports:
      - "6379:6379"
    volumes:
      - redis:/data
    restart: always

volumes:
  postgres:
  redis:

models:
  llm:
    model: ai/llama3.1
    runtime_flags:
      - "--no-prefill-assistant"
